# Python for Data Analysis

### Numpy

NumPy is a linear algebra library for Python. Most other data science libraries in Python rely on it. 

In [3]:
#import 
import numpy as np

#### Numpy Arrays

1-D Vectors or n-D matrices

###### Casting a List to a NumPy array

In [5]:
# 1D Array

# Create a list
myList = [1,2,3]
# Cast it to a NumPy array
arr1 = np.array(myList)
arr1

array([1, 2, 3])

In [71]:
# 2D Array (can be noticed by number of square brackets on either end)

# Create a list
myMatrix = [[1,2,3],[4,5,6],[7,8,9]]
# Cast it to a NumPy array
arr2 = np.array(myMatrix)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###### Creating an array with arange

`arange` is NumPy's built in range function. It takes a start, end, and increment and returns an array containing the specified values

In [8]:
#np.arange(start,stop,Optional:step)
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

###### Creating an array of zeros

In [9]:
# To create a vector, pass a number as the argument
np.zeros(3)

array([0., 0., 0.])

In [10]:
# To create a matrix, pass a tuple as the argument 
np.zeros((3,3)) # np.zeros((rows,cols))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### Creating an array of ones 

In [11]:
# To create a vector, pass a number as the argument
np.ones(4)

array([1., 1., 1., 1.])

In [12]:
# To create a matrix, pass a tuple as the argument 
np.ones((4,4)) # np.ones((rows,cols))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

###### Create an array with linearly spaced data points

In [14]:
# Syntax: np.linspace(start,end,number of points)
np.linspace(0,10,50) # Note: Returns a 1D array

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

###### Create an identity matrix 

An identity matrix has the same number of rows and columns. It has ones across the diagonal and zeros in all other positions.

In [16]:
# Syntax: np.eye(rows/cols)
np.eye(5) # Returns a 2D identity matrix with 5 rows and 5 columns

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###### Creating arrays with random values


In [23]:
# Random decimals in [0.1)

#Syntax: np.random.rand(dim0,dim1,...dimn)
np.random.rand(4,5) # 4x5 array with random values in [0,1)

array([[0.56917302, 0.05407427, 0.52416213, 0.03847885, 0.80021745],
       [0.90001541, 0.14142558, 0.75115883, 0.50821146, 0.98504355],
       [0.54352542, 0.71966944, 0.1630343 , 0.91373674, 0.0627205 ],
       [0.78557284, 0.8020569 , 0.5747332 , 0.54500796, 0.09948941]])

In [24]:
# You can multiply by any number to make the array values in the range [0,n)

# Multiply by 100 to get random uniform percentages 
np.random.rand(4,5) * 100

array([[53.86741984, 36.4077494 ,  8.45523383, 39.42445448, 51.70756889],
       [32.12762217, 93.19454572,  6.74069396, 48.73559963,  6.30002572],
       [61.06957299, 59.67455017, 80.7914452 ,  3.69814625, 23.18610572],
       [ 2.24346398, 83.27183254, 19.90266183, 23.72061949,  0.38115931]])

In [26]:
# Random decimals from a standard normal distribution (Gaussian) centered around 0

# Syntax: np.random.randn(dim0,dim1,...dimn)
np.random.randn(7,4)

array([[-0.15723575, -0.88253217,  0.34465247,  0.46600816],
       [-0.04879528,  2.06707059,  2.90109884,  0.61548412],
       [-1.46275379,  1.47455577,  0.45522763,  0.24555068],
       [ 0.63723559, -0.00855502,  0.55067381,  0.49089246],
       [ 0.19293276,  1.81941795,  1.08784421, -0.61137709],
       [-1.67671716,  0.56413566,  1.11119478, -0.50797801],
       [ 0.67374776,  0.8281145 , -0.14161263,  1.14110179]])

In [30]:
# Random integers in a range 

# Syntax: np.random.randint(start,end,number of points)
np.random.randint(1,100,(10,5)) # Number of points can be a number for 1D vectors or a tuple for 2D vectors

array([[65, 29, 57, 26, 96],
       [98, 55, 29, 87, 13],
       [ 6, 59, 29, 20, 47],
       [76, 51, 91, 36, 52],
       [88, 51, 66, 24, 99],
       [ 5, 48, 75, 31, 88],
       [63, 35, 99, 25, 41],
       [19, 25, 51, 56, 33],
       [78, 77, 24, 66, 51],
       [ 7,  8,  5, 70,  7]])

##### Reshaping an array

In [32]:
# Creage an array of 20 random numbers
arr = np.random.randint(1,100,20)
# Syntax: array.reshape(rows,cols)
arr.reshape(4,5) # reshape the array to 4x5 

array([[27, 12, 33, 52, 34],
       [11, 46, 12, 23, 95],
       [92, 58, 39, 78, 30],
       [39, 52, 22, 17, 98]])

In [33]:
# Note: The total size of the new array must be unchanged
arr.reshape(7,3) # (7x3 = 21) != 20

ValueError: cannot reshape array of size 20 into shape (7,3)

###### Getting the maximum and minimum values in the array 

In [35]:
# Get the maximum value in the array
arr.max()

98

In [36]:
# Get the minimum value in the array
arr.min()

11

In [37]:
# You can get the index of the maximum and minimum values in an array 
arr.argmax() # The maximum value 98 has index 19

19

In [38]:
arr.argmin() # The minimum value 11 has index 5

5

###### Find out the shape of an array

In [40]:
arr.shape # 1D Vector with 20 elements

(20,)

In [41]:
arr = arr.reshape(4,5) # arr is now a 2D array with 4 rows and 5 cols
arr.shape 

(4, 5)

#### Array indexing

Forward indexing `array[0,1, ..., n-1]`

Backward indexing `array[-n, ..., -2, -1]`

In [73]:
arr2 = np.arange(10,20)
print(arr2)
# Syntax: array[index]
arr2[3] # Get the element at index 3

[10 11 12 13 14 15 16 17 18 19]


13

In [48]:
print(arr)
# Syntax: array[row index][col index]
arr[3] # Get the 4th row 

[[27 12 33 52 34]
 [11 46 12 23 95]
 [92 58 39 78 30]
 [39 52 22 17 98]]


array([39, 52, 22, 17, 98])

In [51]:
arr[1][3] # Get the fourth item in the second row

23

In [81]:
# You can also use single bracket notation to index 2D arrays
# Syntax: array[row,col]
arr[1,3]

23

###### Array Slicing

In [53]:
print(arr2)
arr2[3:7] # Get the 4,5,6,7th items

[10 11 12 13 14 15 16 17 18 19]


array([13, 14, 15, 16])

In [62]:
print(arr)
arr[1:3] # Get the second and third rows

[[27 12 33 52 34]
 [11 46 12 23 95]
 [92 58 39 78 30]
 [39 52 22 17 98]]


array([[11, 46, 12, 23, 95],
       [92, 58, 39, 78, 30]])

In [63]:
arr2[-5:] # get the last 5 items

array([15, 16, 17, 18, 19])

In [85]:
# You van grab subsections of arrays

# Grab the top 2x2 right corner of arr
print(arr)
# Syntax: array[rowstart:rowend, colstart:colend]
arr[:2,-2:] # Grab the items in the first two rows and last two columns

[[27 12 33 52 34]
 [11 46 12 23 95]
 [92 58 39 78 30]
 [39 52 22 17 98]]


array([[52, 34],
       [23, 95]])

In [100]:
# bigger example
arr_2d = np.arange(56).reshape(7,8)
print(arr_2d, '\n')

# Grab 12,13,14,20,21,22,28,29,30
arr_2d[1:4,4:7]

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]] 



array([[12, 13, 14],
       [20, 21, 22],
       [28, 29, 30]])

#### Broadcasting

You can change values in a NumPy array with broadcasting

In [75]:
print(arr2)
# Broadcast elements in positions 4,5,6 to 100
arr2[4:7] = 100
print(arr2)

[10 11 12 13 14 15 16 17 18 19]
[ 10  11  12  13 100 100 100  17  18  19]


In [77]:
# Note: Broadcasting on array slices affects the original array (the slice is just a view of the original array)

# Grab a slice of the array
arr2_slice = arr2[4:7]
# Change the values in the slice to 47
arr2_slice[:] = 47
# Show the changed values in slice
print(arr2_slice)
# Values are also changed in original array
print(arr2)

[47 47 47]
[10 11 12 13 47 47 47 17 18 19]


In [80]:
# To leave original array values unchanged

# Copy values into separate array
# Syntax: array.copy()
copy_arr2 = arr2.copy()[7:] 
print(copy_arr2)
# Change the values in the copy
copy_arr2[:] = 42
# Values change in the copy 
print(copy_arr2)
# Values don't change in the original
print(arr2)

[17 18 19]
[42 42 42]
[10 11 12 13 47 47 47 17 18 19]


#### Conditional Selection

In [93]:
# The full array 
print(arr,'\n')
# Create a condition 
condition = arr > 50 # Returns an array with True at the positions whose values are greater than 50 and False elsewhere
print(condition, '\n')

# Use the boolean array to get the values in the array that pass the condition 
arr[condition]

[[27 12 33 52 34]
 [11 46 12 23 95]
 [92 58 39 78 30]
 [39 52 22 17 98]] 

[[False False False  True False]
 [False False False False  True]
 [ True  True False  True False]
 [False  True False False  True]] 



array([52, 95, 92, 58, 78, 52, 98])

In [97]:
# You can also directly pass in the condition to the array index
print(arr)
# Get the values under 50
arr[arr < 50]

[[27 12 33 52 34]
 [11 46 12 23 95]
 [92 58 39 78 30]
 [39 52 22 17 98]]


array([27, 12, 33, 34, 11, 46, 12, 23, 39, 30, 39, 22, 17])

#### Numpy Operations

* Array with Array
* Array with Scalar
* Universal Array Functions

###### Array with Array Addition

In [7]:
import numpy as np

#Create an array 
arr1 = np.arange(20,50,2)
print(arr1, '\n')

#Create another array with the same size
arr2 = np.random.randint(10,40,15)
print(arr2, '\n')

# Add the arrays together
arr1 + arr2 

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48] 

[15 31 39 32 23 21 14 21 22 18 17 14 17 26 25] 



array([35, 53, 63, 58, 51, 51, 46, 55, 58, 56, 57, 56, 61, 72, 73])

In [11]:
# 2D matrix addition

# Create a 4x3 matrix
arr1 = np.arange(42,18,-2).reshape(4,3)
print(arr1, '\n')

# Create another 4x3 matrix
arr2 = np.random.randint(20,40,12).reshape(4,3)
print(arr2, '\n')

#Add the matrix elements together
arr1 + arr2

[[42 40 38]
 [36 34 32]
 [30 28 26]
 [24 22 20]] 

[[26 25 33]
 [29 28 31]
 [27 29 23]
 [20 25 27]] 



array([[68, 65, 71],
       [65, 62, 63],
       [57, 57, 49],
       [44, 47, 47]])

###### Array with Array Subtraction

In [14]:
# Create an array 
arr1 = np.linspace(20,50,4)
print(arr1, '\n')

#Create another array with the same size
arr2 = np.random.rand(4) * 20
print(arr2, '\n')

# Subtract the array elements 
arr1 - arr2 

[20. 30. 40. 50.] 

[18.78247856  1.31739748 13.14952119 14.59439678] 



array([ 1.21752144, 28.68260252, 26.85047881, 35.40560322])

In [21]:
# 2D matrix

# Create a matrix
arr1 = np.linspace(60,80,24).reshape(8,3)
print('First array:\n', arr1, '\n')

#Create another array with the same size
arr2 = np.random.rand(8,3) * 70
print('Second array:\n', arr2, '\n\nSubtracted Array:')

# Subtract the array elements 
arr1 - arr2 

First array:
 [[60.         60.86956522 61.73913043]
 [62.60869565 63.47826087 64.34782609]
 [65.2173913  66.08695652 66.95652174]
 [67.82608696 68.69565217 69.56521739]
 [70.43478261 71.30434783 72.17391304]
 [73.04347826 73.91304348 74.7826087 ]
 [75.65217391 76.52173913 77.39130435]
 [78.26086957 79.13043478 80.        ]] 

Second array:
 [[ 9.03280613 18.00639594 40.37678845]
 [19.73240941 16.35365828 20.23871489]
 [68.80500087 41.26039001 69.37437617]
 [18.73323783 69.83527979 66.31995321]
 [38.24839402 34.3984941  48.45726993]
 [42.01625049 59.40662626 10.99000346]
 [56.17002594 55.14936489 38.26632932]
 [69.5049668  66.04931939 22.43788371]] 

Subtracted Array:


array([[50.96719387, 42.86316927, 21.36234199],
       [42.87628625, 47.12460259, 44.1091112 ],
       [-3.58760957, 24.82656651, -2.41785443],
       [49.09284913, -1.13962762,  3.24526418],
       [32.18638858, 36.90585372, 23.71664311],
       [31.02722778, 14.50641721, 63.79260523],
       [19.48214798, 21.37237424, 39.12497503],
       [ 8.75590277, 13.08111539, 57.56211629]])

###### Array with Array Multiplication

In [23]:
# Create an array
arr1 = np.random.rand(7)
print('First array:\n', arr1, '\n')

#Create another array with the same size
arr2 = np.random.rand(7)
print('Second array:\n', arr2, '\n\nProduct Array:')

# Multiply the array elements 
arr1 * arr2 

First array:
 [0.88560111 0.46987769 0.68559791 0.94035248 0.76055429 0.4718252
 0.35648714] 

Second array:
 [0.4335182  0.1764055  0.84879574 0.38490329 0.09045907 0.93869569
 0.94950076] 

Product Array:


array([0.3839242 , 0.08288901, 0.58193258, 0.36194476, 0.06879903,
       0.44290028, 0.3384848 ])

In [25]:
#2D matrix

# Create a matrix
arr1 = np.random.randint(7,72,(5,3))
print('First array:\n', arr1, '\n')

# Create another matrix with the same size
arr2 = np.random.rand(5,3)
print('Second array:\n', arr2, '\n\nProduct Array:')

# Multiply the array elements 
arr1 * arr2 

First array:
 [[49 33 36]
 [42 37 22]
 [52 56 17]
 [67  7 24]
 [16 64 61]] 

Second array:
 [[0.69789033 0.5821928  0.33641137]
 [0.02175689 0.16357224 0.85062891]
 [0.01408864 0.10874972 0.46611847]
 [0.67697436 0.23362903 0.57643409]
 [0.06567563 0.99173243 0.87757867]] 

Product Array:


array([[34.19662593, 19.21236229, 12.11080946],
       [ 0.91378946,  6.05217284, 18.71383603],
       [ 0.73260907,  6.0899842 ,  7.92401407],
       [45.35728226,  1.63540324, 13.83441827],
       [ 1.05081006, 63.47087568, 53.53229896]])

###### Array with Array Division 

In [27]:
# Create an array
arr1 = np.random.randn(12)
print('First array:\n', arr1, '\n')

# Create another array with the same size
arr2 = np.random.randn(12)
print('Second array:\n', arr2, '\n\nQuotient Array:')

# Divide the array elements 
arr1 / arr2 

First array:
 [-0.66907199  0.35901183  0.02082345 -0.519228    0.13106221 -0.93638848
 -0.53371471 -0.05049385 -0.33833608 -1.12320158  0.4333472  -1.85225355] 

Second array:
 [ 0.62335989 -0.66262247 -1.34924704 -0.82687864  0.53929439  0.59821594
  0.62728036 -1.3926174  -0.71965457  1.87759978 -0.1347179   0.74696933] 

Quotient Array:


array([-1.07333179, -0.54180449, -0.01543339,  0.62793737,  0.24302535,
       -1.56530179, -0.85083917,  0.03625823,  0.47013677, -0.59821139,
       -3.21670103, -2.47969158])

In [28]:
# 2D matrix

# Create a matrix
arr1 = np.random.randn(8,4) * 100
print('First array:\n', arr1, '\n')

# Create another matrix with the same size
arr2 = np.random.randn(8,4) * 10
print('Second array:\n', arr2, '\n\nQuotient Array:')

# Divide the array elements 
arr1 / arr2 

First array:
 [[ 193.30332721  -16.5930582   -50.14593995  -85.16875179]
 [ -18.34843102  219.33703989   62.43735182  -66.35228363]
 [   3.47848411  -21.44142768   75.23731917 -100.74201103]
 [  96.1973034    22.65434075  -47.96457547  -47.94598668]
 [  50.98773807   80.83285328   -9.46995568   75.15554258]
 [ -84.59900417  -54.37463653   86.89710908   96.36566211]
 [ 169.17620802    0.5649174     0.72815064  -16.97834443]
 [ -99.93897292  175.89844652  217.05660701  -36.98806879]] 

Second array:
 [[ -7.2748341    2.72884266   8.29053195  -1.23391759]
 [ -2.99956555   9.18976735   5.09068148 -12.67419254]
 [  2.710901    -9.91470088 -15.26014799   6.25219673]
 [  1.61538946  -3.88788688   2.39733555 -12.80477908]
 [ 17.03211142   3.36100203  10.82016313   1.32371689]
 [ -4.29437567   3.50955539  -8.95018103 -12.62432409]
 [-15.82213567 -16.08895193 -15.26441527  -7.13572105]
 [-21.29185879  12.01154487   9.96964501   5.68095916]] 

Quotient Array:


array([[-2.65715100e+01, -6.08062108e+00, -6.04857930e+00,
         6.90230471e+01],
       [ 6.11702952e+00,  2.38675291e+01,  1.22650282e+01,
         5.23522768e+00],
       [ 1.28314686e+00,  2.16258947e+00, -4.93031386e+00,
        -1.61130584e+01],
       [ 5.95505330e+01, -5.82690327e+00, -2.00074518e+01,
         3.74438219e+00],
       [ 2.99362403e+00,  2.40502245e+01, -8.75213763e-01,
         5.67761455e+01],
       [ 1.96999543e+01, -1.54933120e+01, -9.70897782e+00,
        -7.63333240e+00],
       [-1.06923750e+01, -3.51121316e-02, -4.77024916e-02,
         2.37934531e+00],
       [ 4.69376459e+00,  1.46441152e+01,  2.17717488e+01,
        -6.51088447e+00]])

###### Array with Scalar Operations

The Scalar number is broadcasted to perform the desired operation with every element in the array.

In [31]:
# Addition

# Scalar
a = 3
# Array
arr1 = np.random.randint(1,36,(7,2))
print('Array before:\n', arr1,'\n\nArray after:')
# Add the scalar and the array
arr1 + a

Array before:
 [[25 10]
 [34 19]
 [ 8  8]
 [22  3]
 [ 2 11]
 [20 14]
 [ 7 17]] 

Array after:


array([[28, 13],
       [37, 22],
       [11, 11],
       [25,  6],
       [ 5, 14],
       [23, 17],
       [10, 20]])

In [34]:
# Subtraction
print('After Subtraction:') 
arr1 - a

After Subtraction:


array([[22,  7],
       [31, 16],
       [ 5,  5],
       [19,  0],
       [-1,  8],
       [17, 11],
       [ 4, 14]])

In [35]:
# Multiplication
print('Multiplication:') 
arr1 * a

Multiplication:


array([[ 75,  30],
       [102,  57],
       [ 24,  24],
       [ 66,   9],
       [  6,  33],
       [ 60,  42],
       [ 21,  51]])

In [41]:
# Division
print('Division:') 
arr1 / a

Division:


array([[ 8.33333333,  3.33333333],
       [11.33333333,  6.33333333],
       [ 2.66666667,  2.66666667],
       [ 7.33333333,  1.        ],
       [ 0.66666667,  3.66666667],
       [ 6.66666667,  4.66666667],
       [ 2.33333333,  5.66666667]])

In [40]:
# Caution: NumPy only issues a watning for certain arithmetic errors
    
# Division by 0
arr2 = np.arange(0,14,1).reshape(7,2)
arr1/arr2 # issues a warning and returns infinity for the first value (divided by 0)

<ipython-input-40-39bd96c249df>:5: RuntimeWarning: divide by zero encountered in true_divide
  arr1/arr2


array([[        inf, 10.        ],
       [17.        ,  6.33333333],
       [ 2.        ,  1.6       ],
       [ 3.66666667,  0.42857143],
       [ 0.25      ,  1.22222222],
       [ 2.        ,  1.27272727],
       [ 0.58333333,  1.30769231]])

###### You can also do exponent and modular operations with arrays

In [42]:
# Exp with scalar
arr1 **3

array([[15625,  1000],
       [39304,  6859],
       [  512,   512],
       [10648,    27],
       [    8,  1331],
       [ 8000,  2744],
       [  343,  4913]])

In [43]:
# mod with scalar
arr1 % 2

array([[1, 0],
       [0, 1],
       [0, 0],
       [0, 1],
       [0, 1],
       [0, 0],
       [1, 1]])

In [44]:
# Exp with array 
arr1 ** arr1

array([[-6776596920136667815,          10000000000],
       [-5296008294479953920,  6353754964178307979],
       [            16777216,             16777216],
       [ 4981753131911086080,                   27],
       [                   4,         285311670611],
       [-2101438300051996672,    11112006825558016],
       [              823543, -2863221430593058543]])

In [46]:
# mod with array
arr1 % arr2

<ipython-input-46-845b0029d311>:2: RuntimeWarning: divide by zero encountered in remainder
  arr1 % arr2


array([[0, 0],
       [0, 1],
       [0, 3],
       [4, 3],
       [2, 2],
       [0, 3],
       [7, 4]])

#### Other Universal Array Functions

Functions that can broadcast to every element in the array. 

The list can be found here: https://numpy.org/doc/stable/reference/ufuncs.html

###### Square Root

`sqrt(array)`

In [47]:
# Take the square root
print('Base Array:\n', arr1, '\n\nSquare Root Array')
np.sqrt(arr1)

Base Array:
 [[25 10]
 [34 19]
 [ 8  8]
 [22  3]
 [ 2 11]
 [20 14]
 [ 7 17]] 

Square Root Array


array([[5.        , 3.16227766],
       [5.83095189, 4.35889894],
       [2.82842712, 2.82842712],
       [4.69041576, 1.73205081],
       [1.41421356, 3.31662479],
       [4.47213595, 3.74165739],
       [2.64575131, 4.12310563]])

###### Exponential

`exp(array)`

In [48]:
# Raise to e
print('Base Array:\n', arr1, '\n\nExponent Array')
np.exp(arr1)

Base Array:
 [[25 10]
 [34 19]
 [ 8  8]
 [22  3]
 [ 2 11]
 [20 14]
 [ 7 17]] 

Exponent Array


array([[7.20048993e+10, 2.20264658e+04],
       [5.83461743e+14, 1.78482301e+08],
       [2.98095799e+03, 2.98095799e+03],
       [3.58491285e+09, 2.00855369e+01],
       [7.38905610e+00, 5.98741417e+04],
       [4.85165195e+08, 1.20260428e+06],
       [1.09663316e+03, 2.41549528e+07]])

###### Maximum and Minimum

In [50]:
print('Max is:', np.max(arr1))
print('Min is:', np.min(arr1))

Max is: 34
Min is: 2


###### Trigonometric Functions (sin, cos, tan ...)

In [51]:
# pass in every element of arr1 into sin
np.sin(arr1)

array([[-0.13235175, -0.54402111],
       [ 0.52908269,  0.14987721],
       [ 0.98935825,  0.98935825],
       [-0.00885131,  0.14112001],
       [ 0.90929743, -0.99999021],
       [ 0.91294525,  0.99060736],
       [ 0.6569866 , -0.96139749]])

In [55]:
# Geyt the value for every element of arr1 in degrees
np.degrees(arr1)

array([[1432.39448783,  572.95779513],
       [1948.05650344, 1088.61981075],
       [ 458.3662361 ,  458.3662361 ],
       [1260.50714929,  171.88733854],
       [ 114.59155903,  630.25357464],
       [1145.91559026,  802.14091318],
       [ 401.07045659,  974.02825172]])

In [58]:
# Get the value for every element of arr1 in radians
arr1 = np.radians(arr1)
arr1

array([[0.00761544, 0.00304617],
       [0.01035699, 0.00578773],
       [0.00243694, 0.00243694],
       [0.00670158, 0.00091385],
       [0.00060923, 0.00335079],
       [0.00609235, 0.00426464],
       [0.00213232, 0.0051785 ]])

###### Logarithmic functions (log, log2, log10 ...)

In [62]:
# natural log
np.log(arr1)

array([[-4.87757811, -5.79386884],
       [-4.57009341, -5.15201495],
       [-6.01701239, -6.01701239],
       [-5.00541148, -6.99784164],
       [-7.40330675, -5.69855866],
       [-5.10072166, -5.4573966 ],
       [-6.15054378, -5.26324059]])

In [63]:
# log base 2
np.log2(arr1)

array([[ -7.03685774,  -8.35878584],
       [ -6.59325109,  -7.43278642],
       [ -8.68071393,  -8.68071393],
       [ -7.22128232, -10.09575143],
       [-10.68071393,  -8.22128232],
       [ -7.35878584,  -7.87335901],
       [ -8.87335901,  -7.59325109]])

In [64]:
# log base 10 
np.log2(arr1)

array([[ -7.03685774,  -8.35878584],
       [ -6.59325109,  -7.43278642],
       [ -8.68071393,  -8.68071393],
       [ -7.22128232, -10.09575143],
       [-10.68071393,  -8.22128232],
       [ -7.35878584,  -7.87335901],
       [ -8.87335901,  -7.59325109]])